### ISSUE TITLE
아이디 찾기에 대한 질문

### ISSUE THREAD

**Issue by kimchang0** [senor14/StudyRoadMap#16]
아이디 찾기가 필요할까요? 의견 부탁드립니다~

**Comment by senor14** [comment]
네 있으면 좋을 것 같네요

**Comment by kimchang0** [comment]
@senor14 감사합니다!

**Comment by kimchang0** [comment]
다른 분들도 의견 부탁드립니다~~

**Comment by SBkim12** [comment]
일단 기능 구현 해두면 좋을듯!

**Comment by kimchang0** [comment]
넵 나머지 두 분도 의견 주세요~

2021년 9월 30일 (목) 오후 11:15, SBkim12 ***@***.***>님이 작성:

**Comment by hkh1213** [comment]
가능하다면 좋죠 ^_^

**Comment by 2changjon** [comment]
바로바로 답변은 어렵지만 최대한 빠른 답변을 하겠습니다.
